# Generated by Django 5.0.4 on 2026-04-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('pomodoro_sessions', models.PositiveIntegerField(default=0)),
                ('study_time_minutes', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Quotidienne',
                'verbose_name_plural': 'Progressions Quotidiennes',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
