[pytest]
DJANGO_SETTINGS_MODULE = studyflow.settings
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers
markers =
    slow: marque les tests lents
    integration: tests d'intégration
